### ISSUE TITLE
Fix Travis - coverage check

### ISSUE THREAD

**Issue by MaxGroenenboom** [eishub/tygron#101]
I think Travis doesn't correctly check the coverage anymore. It only does a `mvn test` now, but that doesn't check the coverage. This should be fixed asap before the coverage starts decreasing.

(Snapshot of the travis.yml at the time of writing): https://github.com/eishub/tygron/blob/e9ad712f6ddd0101fba244dc1579d366e762d98e/.travis.yml

~~I think doing just a `mvn cobertura:check` would be enough, as that call would most probably fail when the tests fail (testing this right now).~~
Too bad, looks like `mvn cobertura:check` succeeds when tests are failing.

**Comment by MaxGroenenboom** [comment]
It looks like it is impossible to both check if all tests succeed and if the coverage is sufficient in a single run, so we still would have to run all tests twice...

**Comment by levilime** [comment]
Yes for example: https://stackoverflow.com/questions/5142254/maven-cobertura-unit-test-failed-but-build-success, will add both tests for unit testing and cobertura seperately again in #102

**Comment by MaxGroenenboom** [comment]
Yeah it looks like that's unavoidable (and apparently should be). I did find something though, some report files are generated in the target in which it is very easy to find a failing test, we could use those. I don't think this small performance upgrade is worth the hassle though
