### ISSUE TITLE
Percept suggestion - my_stakeholder_id/1

### ISSUE THREAD

**Issue by klikooo** [eishub/tygron#11]
~~`self/1 - self(<id>)`~~ Changed to `my_stakeholder_id(<ID>)` because Wouter did not like self.

`<id>` - The ID of the stakeholder you are.

This is a send once percept.

**Comment by MaxGroenenboom** [comment]
Wouter thinks self is unclear, ideas how we could call this?

**Comment by MarcianoJ** [comment]
own_id?
