### ISSUE TITLE
Percept Suggestion: Indicator_link/4

### ISSUE THREAD

**Issue by StefanV7** [eishub/tygron#12]
`indicator_link/4 - indicator_link(<indID>,<stakeIDs>,<name>,<weight>)`

Gives info about an indicator and shows its ID, which again can be used to find other info about the indicator. It also links stakeholders to the indicators.

`<indID>` - ID of the indicator. Global indicators should have the same ID for each stakeholder, but a stakeholder-specific indicator like housing/budget should have a different ID for each stakeholder.
`<stakeIDs>` - ID of the stakeholders to which the indicator belongs.
`<name>` - Name of the indicator.
`<weight>` - Weight of indicator, determines how important it is.

**Comment by NickTUD** [comment]
Percept has been implemented by Danshal and is visible in PR #22
