### ISSUE TITLE
Percept Suggestion: zone_link/4

### ISSUE THREAD

**Issue by MHMCD** [eishub/tygron#13]
`zone_link/4 - zone_link(<zoneID>, <indID>, <cur_Val>, <tar_Val>)`

Gives information about the indicators in a zone with their current value and target value.

`<zoneID>` - ID of the zone
`<indID>` - ID of a zone's indicator. 
`<cur_Val>` - Current value for the zone indicator.
`<tar_Val>` - Target value for the zone indicator.

**Comment by JoshCode** [comment]
Depends on #53

**Comment by MaxGroenenboom** [comment]
@JoshCode I don't think it is a good idea to just move the issues that weren't implemented in a milestone to the next milestone. Now we lost track of what should have been finished already and what should be finished before next friday, thus losing the pressure on the issues and pull requests from last week.

**Comment by levilime** [comment]
I agree with Max, this is confusing and I'm starting to get worried about #53 which is very important for all teams and should be seperate from #13.

**Comment by spiderbiggen** [comment]
you can on the pull request page, instead of selecting your branch to compare with you specify the commit by typing it eg commit 7f7ca56

**Edit** whoop wrong issue :stuck_out_tongue:

**Comment by MaxGroenenboom** [comment]
@spiderbiggen  Didn't you intend to leave that comment on #60?

**Comment by spiderbiggen** [comment]
I did...

**Comment by JoshCode** [comment]
Resolved, #61 was merged.
