### ISSUE TITLE
Percept suggestion - land/2

### ISSUE THREAD

**Issue by NickTUD** [eishub/tygron#17]
`land/2 - land(<shID>, [<multiPolygon>])`

For a stakeholder, it should be known what land is theirs and what land belongs to other stakeholders. This way other stakeholders can decide whether or not they need to buy extra land or that they can just build on the land they already own.

`<shID>` - ID of the stakeholder the land belongs to
`<multiPolygon>` - A polygon representing one piece of land.

This is subject to change though, if another group has a better idea.

**Comment by spiderbiggen** [comment]
This exists in the current environment as `land/2 - land(<landId>, <shID>, [<multiPolygon>])`
`<landId>` - ID of the piece of land.
`<shID>` - ID of the stakeholder the land belongs to
`<multiPolygon>` - A polygon representing one piece of land.
