### ISSUE TITLE
Percept suggestion - popup/?

### ISSUE THREAD

**Issue by NickTUD** [eishub/tygron#18]
`popup/? - popup(<popupID>, .....)`

We should think about what is needed in popup percepts as these percepts are crucial for the municipality. Without this, all stakeholders beside the municipality can make plans for constructions to the municipality, but the municipality cannot approve the construction then for example.

**Comment by levilime** [comment]
I talked with Wouter, he thinks it's a bad idea to call this popup, and I do too. Let's call a percept where someone has to give permission for the building of something "buildpermit".

**Comment by levilime** [comment]
Team Danshal will implement this for the next sprint.

**Comment by MaxGroenenboom** [comment]
We should first brainstorm with all groups together what is should do exactly

**Comment by levilime** [comment]
@MaxGroenenboom we have discussed this on friday with all groups. Team Danshal will start hacking for the upcoming sprint :+1:

**Comment by MaxGroenenboom** [comment]
@levilime True, but that comment was from before the meeting on friday

**Comment by levilime** [comment]
:+1:

**Comment by spiderbiggen** [comment]
So what is the progress on this, is this the same as the requests percept?

**Comment by levilime** [comment]
The percept is indeed now called request.

**Comment by JoshCode** [comment]
So shouldn't this be closed, as it looks really weird to have a Sprint 5 that is 15 days overdue right now?

\- CodeFox [![CF](http://i.imgur.com/dyOqeMH.png)](http://github.com/CodeFoxNL)

**Comment by levilime** [comment]
The percept is now called request and additional features for requests are implemented in #81 this is merged so this issue is resolved.
