### ISSUE TITLE
Using polygons in the GOAL agent

### ISSUE THREAD

**Issue by nskartoredjo** [eishub/tygron#30]
Frank discouraged us to use polygons in GOAL, but it seems to be necessary for features like building on certain locations etc. What do we prefer?

**Comment by levilime** [comment]
I'm of the opinion that the Goal agent should be allowed to have good control over where he wants a building placed. But there can be very little geometrical computations on Goal so I think it would be best if polygons are implied through the connector but never explicitly received by the Goal agent

**Comment by nskartoredjo** [comment]
It is hard to say something like "build there" if you don't know where "there" is and if you are able to build "there". You could perhaps make a action which builds on the ideal location if you want to build something with a amount of flour size, somewhere in a specified area (giving a simple polygon square)?

**Comment by levilime** [comment]
Yes something like that, there is to my knowledge already functionality provided for if you want to build it is placed somewhere where it's possible in the connector. An important feature would be to expand this to zones, for indicators that are zone independent or need to get a certain treshold for each zone.
