### ISSUE TITLE
Update the SDK.

### ISSUE THREAD

**Issue by MaxGroenenboom** [eishub/tygron#35]
The connector is currently broken because the SDK has been updated, and the server refuses any connection with out-of-date SDK's.

**Comment by Wouter1** [comment]
@MaxGroenenboom  @HarmGriffioen  @levilime 

In general I do not respond to github tickets. 

Please discuss issues with the assistents. Maybe Harm handles tickets assigned to him. The assistents will then forward to me if necessary. I do not work directly on tickets on github as we have our own ticket system to ensure issues are handled privately (#3920).

Regarding the issue, I did not hear about server changes from Frank. I will check what's going on and you will hear back from the assistents.
