### ISSUE TITLE
Please make the context branch protected.

### ISSUE THREAD

**Issue by levilime** [eishub/tygron#36]
This way we can be sure that progress on context branch won't be destroyed.

**Comment by HarmGriffioen** [comment]
protected from whom? it can only be accessed by colaborators, which is everyone doing the contextproject. You are not destroying your own stuff are you?

**Comment by levilime** [comment]
Thanks for making the branch protected :+1:

**Comment by levilime** [comment]
Oh wait didn't see it right, it is not yet protected, reasons for making it protected. We are 25 persons having our work cummulated on one branch. I think it's fine to put in the extra safety check. What if someone found a new cool git command and forces this accidentally on the context branch of eishub/tygron (maybe he mistook the remote link for his own repo) A lot more scenario's could be sketched, it would be recoverable because everyone has the context branch on their own repo but this would be a hassle, also because travis builds and PR history is dislinked. I think making the context branch is a logical choice. It might not be about me destroying my stuff, it is about someone like me destroying my stuff :smile:

**Comment by MaxGroenenboom** [comment]
This can be closed I think? A PR can easily be reverted and commits, if someone accidentally forgets to branch, as well. I'm sure all of us can handle the responsibility, and otherwise it won't be much of a problem to revert any wrong changes.

**Comment by levilime** [comment]
@MaxGroenenboom Yes this is the case when the branch is protected. If it is not protected anyone with write access can make irreversible changes to the branch. But if my opinion of protecting the branch is not shared this can be closed.

**Comment by MaxGroenenboom** [comment]
I now see what you mean, we are apparently able to delete this branch? That shouldn't be possible ^^
