### ISSUE TITLE
Target value of percept indicator/3 is always 0.0

### ISSUE THREAD

**Issue by JaspervanTilburg** [eishub/tygron#39]
When I try to use the indicator/3 percept the 3 value, the target value, always is 0.0.

**Comment by NickTUD** [comment]
We (Danshal) had already noticed it and are looking into it for now, but we're not sure where the problem lies. We think a wrong method is used in the translator but as I said we're not sure.

**Comment by JoshCode** [comment]
We believe this will be fixed by #53 

\- CodeFox [![CF](http://i.imgur.com/dyOqeMH.png)](http://github.com/CodeFoxNL)

**Comment by JoshCode** [comment]
This is probably fixed now.

**Comment by tvleest** [comment]
This issue can be closed right?

**Comment by MaxGroenenboom** [comment]
I think so.
