### ISSUE TITLE
Checkstyle redundant checks.

### ISSUE THREAD

**Issue by MaxGroenenboom** [eishub/tygron#44]
There are some checks in the checkstyle configuration that don't really add much to the quality of the code in my opinion, or would create a too large gap in code quality between the original connector and the added code.

These are the checks that I think aren't necessary for our project:
- Module JavadocPackage - None of the packages have this file, so it would benefit the connector if we wouldn't create these files.
-  Module JavadocVariable - I have never seen a variable with javadoc, if it is really needed I suppose the creator of the variable will add it regardless of checkstyle...
- The linelength could be a bit larger, to allow for a greater amount of lines to be passable.
- Module DesignForExtension - Just a useless check, correct me if I'm wrong.

I hope people agree with these changes and that they can be implemented soon.

**Comment by spiderbiggen** [comment]
I agree with all of these

**Comment by klikooo** [comment]
I also agree!

**Comment by levilime** [comment]
Sounds good, these changes will be added in #40 where when merged checkstyle starts influencing the build. Linelength will be 120 instead of 80.
