### ISSUE TITLE
add functionID to building percept

### ISSUE THREAD

**Issue by dionytadema** [eishub/tygron#45]
in order to percept if and how much AZC's the municipality constructed we need to be able to retrieve the function id of a building

suggested building percept would than be building(Id, Name, OwnerID, ConstructionYear, Categories, FunctionID, Floors)

**Comment by MaxGroenenboom** [comment]
Can't a building have multiple functions? Like shops on the ground floor and the upper floors apartments.

**Comment by dionytadema** [comment]
No a building can only have one function

**Comment by MaxGroenenboom** [comment]
Seems like you're right, I could've sworn I saw a building in the engine once with multiple functions ^^

**Comment by MaxGroenenboom** [comment]
The amount of units or floorsize is already used in an indicator I suppose? Why not use that indicator instead of letting the agent find it out itself?

**Comment by dionytadema** [comment]
that is a custom indicator and those are broken right now, and even if they would work it is still usefull to be able to check a building for it's function.

I already have the changed percept working localy so i can make a pr anytime others agree with this issue

**Comment by MaxGroenenboom** [comment]
True, I'm in favor of this enhancement anyways.
