### ISSUE TITLE
Intro of vhproject Tu Delft tygron case needs proper introduction slides.

### ISSUE THREAD

**Issue by levilime** [eishub/tygron#47]
It would be nice to have some text there as too which stakeholders are present and what they are supposed to do.

**Comment by MaxGroenenboom** [comment]
I can do that

English or dutch?

**Comment by levilime** [comment]
OK, nice, then you can assign yourself the ticket

**Comment by MaxGroenenboom** [comment]
So should it be in english or dutch? :P

**Comment by levilime** [comment]
Dunglish :smile:

**Comment by levilime** [comment]
But I think Dutch is the way to go for the description

**Comment by MaxGroenenboom** [comment]
Yeah just making sure :)

**Comment by MatthijsJWH** [comment]
To be honest, I think they should be in English since we also need to give a demo to Bacchelli, and possibly also other non-dutch speakers

**Comment by MaxGroenenboom** [comment]
I just made it in Dutch, feel free to translate it.

**Comment by MaxGroenenboom** [comment]
Also I think each group should add a good text for their own stakeholder and indicators, I'm sure I can't describe every stakeholder in the detail their own group could.

**Comment by MatthijsJWH** [comment]
I will translate them later tonight or possibly tomorrow

**Comment by MaxGroenenboom** [comment]
Pretty much everything is in Dutch though, so if you want to be consistent, everything would have to be translated.

**Comment by MaxGroenenboom** [comment]
I think this has been finished? Please review in the engine.
