### ISSUE TITLE
Parse Excel EXPLANATION in the connector

### ISSUE THREAD

**Issue by JoshCode** [eishub/tygron#53]
This can be used by all indicators to return their current value.

Assigned to @MHMCD and @JoshCode

This is a dependency for #13 

\- CodeFox [![CF](http://i.imgur.com/dyOqeMH.png)](http://github.com/CodeFoxNL)

**Comment by levilime** [comment]
All groups need this for the presentation this friday. How is the progress of this ticket, will you be able to make a pull request today?

**Comment by JoshCode** [comment]
Resolved, #61 was merged.
