### ISSUE TITLE
Get a list of best places to build in

### ISSUE THREAD

**Issue by MarcianoJ** [eishub/tygron#56]
To get our virtual human to build in a place that makes sense we need the connector to provide a list of best places to build in. The agent should be able to do an action call in order to get the percept containing those places.

**Comment by MaxGroenenboom** [comment]
This is possible now, but there won't be a PR yet to this branch (because of merge issues). If your group really badly needs this functionality, please check out the https://github.com/Denpeer/tygron/tree/getRelevantAreas branch.

**Comment by MaxGroenenboom** [comment]
There now is a pull request for this issue: #86

**Comment by MaxGroenenboom** [comment]
Pull request has been merged, issue can be closed.
