### ISSUE TITLE
Add Multipolygon to building percept

### ISSUE THREAD

**Issue by tvleest** [eishub/tygron#57]
To be able to upgrade a building we need the multipolygon describing the area of that building.

building(Id, Name, OwnerID, ConstructionYear, Categories, FunctionID, Floors, Multipolygon)

Unless someone has a better solution?

**Comment by levilime** [comment]
I agree this solves the problem for upgrading :+1:

**Comment by MaxGroenenboom** [comment]
Don't buildings have an ID as well? I suppose that could also be used instead of the polygon. [edit: apologies for the email formatting]

**Comment by tvleest** [comment]
Thats not how the action currently works in the SDK, it needs a multipolygon.

`@EventParamData(desc = "Plan the upgrade of buildings in the given polygon in the MAQUETTE map", params = { "Stakeholder ID",
            "Upgrade Type ID", "Multipolygon describing the upgrade area" })
    @EventIDField(links = { "STAKEHOLDERS", "UPGRADE_TYPES" }, params = { 0, 1 })
    BUILDING_PLAN_UPGRADE(ClientTerms.ACTION_LOG_UPGRADE, Integer.class, Integer.class, MultiPolygon.class),`

**Comment by MaxGroenenboom** [comment]
Ah, it is probably possible to upgrade only a part of a building then? That is pretty nice.
It is also possible of course to create your own action that fetches the multipolygon for you, having only the buildingID as parameter.

**Comment by spiderbiggen** [comment]
@maxgroenenboom i don't think it is possible to get a result from an action. Correct me if I'm wrong though.

**Comment by MaxGroenenboom** [comment]
I'm not talking about getting a result from an action? What I mean is defining a new action, that then calls the original action.

**Comment by levilime** [comment]
@MaxGroenenboom I don't think such an action is possible, because actions are predefined in the environment. By design an agent does an action and then through perceiving the environment next cycle he can deduce what effect is action has. He can't get a response, as spiderbiggen already said.

**Comment by spiderbiggen** [comment]
It might be possible but i don't think that adding a new action is the easiest way to do this.

**edit** ... that was the wrong button

**Comment by MaxGroenenboom** [comment]
I think it is pretty easy to do this. I am now building a list of actions the PerformAction function in TygronEntity.java will look through before trying the server actions, thus making it possible to create your own actions, or even override server actions.

**Comment by tvleest** [comment]
Sounds like that might be a better solution.

**Comment by MaxGroenenboom** [comment]
So, this isn't as easy as it should be, as the PerformAction method isn't called at all when a non-sdk action is called. Even when I add my custom action to the sdk (temporarily, just for testing), it still doesn't work...

**Comment by spiderbiggen** [comment]
Can you push your code to a branch so i can take a look?

**Comment by MaxGroenenboom** [comment]
Sure, you can find the branch here: https://github.com/Denpeer/tygron/tree/getRelevantAreas
Brace yourself, some of it will be very ugly code, it wasn't my intention to publish this :P

**Comment by MaxGroenenboom** [comment]
Rico has found the cause of the errors, Line 87 in EisEnv.java, I am going to see if I can get it to work now.

**Comment by tvleest** [comment]
We've added multiPolygon to our own fork, so we can at least demo something friday.
If other groups are interested we could make a PR out of it.
It does use powermockito though. #51 
Here is a travis build log https://travis-ci.org/spiderbiggen/tygron/builds/134122390

**Comment by tvleest** [comment]
#68 fixed this
