### ISSUE TITLE
Request percept is broken and needs be fixed

### ISSUE THREAD

**Issue by levilime** [eishub/tygron#62]
From  #50 onward percepts for requests are not brought into the Goal Bot.

**Comment by klikooo** [comment]
What is the request percept?

**Comment by levilime** [comment]
requests([<request>]), it is to get all requests for buildings etc from another stakeholder.

**Comment by levilime** [comment]
I have gotten the request percept back by invoking connectstakeholder at the start of notifyReady function in TygronEntity. Will make an attempt at making a fix where the my stakeholder percept stays online, but if there is a large discrepancy then I will choose requests percept functionality over my stake holder id

**Comment by MaxGroenenboom** [comment]
Has this been fixed?

**Comment by levilime** [comment]
Yes this was fixed in #79 and functionality was extended in #81
