### ISSUE TITLE
Merge master with current context

### ISSUE THREAD

**Issue by spiderbiggen** [eishub/tygron#63]
As a developer
I want to use the latest release
So I can develop a good environment.

**Comment by MaxGroenenboom** [comment]
@Klikooo and @nskartoredjo have already worked on this.

**Comment by spiderbiggen** [comment]
ah ok

**Comment by Wouter1** [comment]
The idea was that the context project works in its own module, instead of the environment module. This would make merges with master updates much easier.

I dont see this idea materialized yet. Are there problems with this ?

**Comment by MaxGroenenboom** [comment]
@Wouter1 @spiderbiggen is working on this. I think it has almost been finished, if it isn't finished already. We postponed it for a week because we didn't want to risk not having a demo ready.

**Comment by spiderbiggen** [comment]
@wouter1 I have been working over the weekend to split it off into a seperate module, but right now there is quite a bit of duplicate code with the tygronenv module, while this isn't a problem it also isn't very good

**Comment by Wouter1** [comment]
I assume that if you would extend the tygronenv module, you can avoid the duplication?

**Comment by Wouter1** [comment]
(or, call the functionality of tygron env if you dont want to extend)

**Comment by spiderbiggen** [comment]
For the most part i probably could

**Comment by spiderbiggen** [comment]
Some of the duplication is in the eventhandler where some of the methods we could use like isForMe are private so extending it won't help me with that

**Comment by Wouter1** [comment]
We can consider changing them to protected

**Comment by Wouter1** [comment]
Please ask Harm if you need changes in master. He will then check if all teams agree and forward the request to me for implementation

**Comment by spiderbiggen** [comment]
@Wouter1 will do, will look at what changes I'd like to see

**Comment by klikooo** [comment]
@HarmGriffioen We want to return a Percept instead of void in the performAction function in TygronEntity.java
