### ISSUE TITLE
Toggling percepts to enable goal "percept mocking"

### ISSUE THREAD

**Issue by Denpeer** [eishub/tygron#64]
It is currently possible to "mock" a percept for testing purposes in the goal test2g files. But since the tygron environment keeps sending the actual percepts this isn't usable yet.
We should create a action for the agent so it can toggle certain percepts.

**Comment by MaxGroenenboom** [comment]
This is implemented and merged now.

**Comment by Denpeer** [comment]
not yet. Should close automatically when it's merged.

**Comment by MaxGroenenboom** [comment]
My bad, I thought it was merged as it should have been by now.
