### ISSUE TITLE
Stakeholders have to confirm with Municipality for building permit.

### ISSUE THREAD

**Issue by levilime** [eishub/tygron#70]
To get a building approved the stakeholder needs to gain a build permit for a building through the municipality. In the tygron interface you click on a building and then through the popup say yes to ask for a permit. The same action has to be implemented through the connector.

**Comment by Wouter1** [comment]
Notice that in the confiirm action is already available (it always was).  The trick is to get the request percept that notifies the agent that a permit needs to be confirmed. You can check the TwoStakeholders.mas2g.

**Comment by levilime** [comment]
Thanks, I have indeed noticed the permit percept when a stakeholder builds something. This is then resolved.
