### ISSUE TITLE
Finding a piece of land to buy.

### ISSUE THREAD

**Issue by tvleest** [eishub/tygron#75]
When buying a piece of land atm, we have no way to figure out what Multipolygon to buy.
A percept with a list of Multipolygons or a custom action might solve this.

**Comment by MaxGroenenboom** [comment]
An action has been made for that kind of query, it hasn't been merged yet though.

**Comment by tvleest** [comment]
So we could make a similar query for this issue?

**Comment by MaxGroenenboom** [comment]
Yes, please add a new custom get relevant areas action for that. `MapUtils` contains a lot of methods you will probably want to use.
