### ISSUE TITLE
Percept Suggestion: Indicators/3

### ISSUE THREAD

**Issue by StefanV7** [eishub/tygron#8]
`indicators/3 - indicators(<indID>, <currentValue>, <targetValue>)`

As a GOAL bot programmer I want to be able to percept how far my indicators have progressed as well as the target value that needs to be achieved, so that I can see if any performed actions have improved or decreased an indicator score.

`<indID>` - ID of the indicator. Global indicators should have the same ID for each stakeholder, but a stakeholder-specific indicator like housing/budget should have a different ID for each stakeholder.
`<currentValue>` - Current value of the indicator
`<targetValue>` - Target value of the indicator

**Comment by NickTUD** [comment]
Percept has been implemented by Danshal and is visible in PR #22
