### ISSUE TITLE
Percept suggestion - zone/6

### ISSUE THREAD

**Issue by nskartoredjo** [eishub/tygron#9]
`zone/6 - zone(<zone_ID>,<name>,<size>,<max_floors>, <allowed_catagories>, <function_ID>)`

`<zone_ID>` - ID given to the zone
`<name>` - Name of the zone
`<max_floor>` - The maximum allowed amount of floors to be set for the zone
`<size>` -  The Amount of squared meters of zone ground
`<allowed_catagories>` - The allowed catagories of the zone
`<function_ID>` - The function id of the zone 

General info about the different zones in the map.

**Comment by NickTUD** [comment]
- ~~What's the point of the `<function_ID>`? [Tygron wiki](http://support.tygron.com/wiki/Zoning#Allowed_zoning_function_types) doesn't show that this is something in the properties of a zone.~~
- Isn't it important to denote that `<allowed_categories>` should be a list of `<category>` (where `<category>` is an allowed category of buildings which can be built in the zone)?

**Comment by jannelie** [comment]
wat wordt er bedoeld met `<function_ID>`, is dit een lijst met ID's voor elke functie die mogelijk is voor die zone, of wordt er iets anders mee bedoeld?

**Comment by TomBrunner** [comment]
Het lijkt erop dat categories al beschrijft wat er wel/niet gebouwt mag worden. En functies zijn alleen de functies voor het bouwen van dingen. Dus daarom lijkt het me dat functies weggelaten zou moeten worden.

**Comment by jannelie** [comment]
Ik denk dat dit een goed idee is, omdat je niet onnodige informatie wilt hebben.

**Comment by MaxGroenenboom** [comment]
Hoe weet mijn agent in welke categorie een functie zit?

**Comment by jannelie** [comment]
Een functie heeft een lijst met categorieen waartoe die fubctie behoort

**Comment by MaxGroenenboom** [comment]
Maar voor functies is geen percept toch?

**Comment by jannelie** [comment]
Ja die stond er al in

**Comment by MaxGroenenboom** [comment]
oh my bad, ik gebruik nu de issue tracker als overzicht van de percepts, omdat sommige percepts opnieuw gedefinieerd zijn

**Comment by MaxGroenenboom** [comment]
Volgens mij zijn we dinsdag tot de conclusie gekomen though dat we functions los meesturen om overhead in de agent te verminderen (correct me if I'm wrong)

**Comment by jannelie** [comment]
Dat zou ik moeten navragen, maar wij kregen het idee dat functies opnieuw meesturen juist overhead gaf.

**Comment by MaxGroenenboom** [comment]
ja in een database klopt dat, maar hier maakt memory overhead minder uit, dus was het efficienter om dingen er meerdere keren in te hebben.
Ik vond het zelf ook beter om alleen categories te doen, maar waarschijnlijk is het met functies erbij wel sneller voor de agent.

**Comment by jannelie** [comment]
oke, dan zullen we proberen om die functie ids weer erin te stoppen.

**Comment by jannelie** [comment]
We hebben er nog eens goed naar gekeken,, maar het toevoegen van functie Id's levert weinig voordeel. Je kunt heel gemakkelijk met de lijst van categories de juiste functies vinden door het percept van functies. Dit haal je één keer binnen, en anders geef je elke keer van de zone alle functies mee die je kunt doen. Terwijl je met categories dezelfde informatie hebt. Daarom hebben we het percept veranderd naar zone/5 en de lijst met funcite ID's weggelaten - Crash Test Dummies

**Comment by MaxGroenenboom** [comment]
Ik vind het prima, dat was in eerste instantie al hoe ik het wilde. Dinsdag hebben we besloten het op de oude manier te doen dus vandaar dat het er zo in stond ;)
Ik zou ook zorgen dat de beschrijving hier nog klopt, en misschien een performance test doen om te zien welke methode sneller is? Ik weet niet of dat haalbaar is in goal hoor, maar het is een poging waard.
